# Generated by Django 6.0.5 on 2026-06-18 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Present', max_length=20)),
                ('teammates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.teammates')),
            ],
        ),
    ]
