# Generated by Django 6.0.6 on 2026-06-22 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='unregistered_log',
            new_name='UnregisteredLog',
        ),
        migrations.AddField(
            model_name='teammates',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammates',
            name='division',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teammates',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teammates',
            name='is_fully_registered',
            field=models.BooleanField(default=False),
        ),
    ]
