# Generated by Django 6.0.5 on 2026-06-20 07:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfidlog',
            name='uid',
        ),
        migrations.AddField(
            model_name='rfidlog',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rfidlog',
            name='rfid_number',
            field=models.CharField(default='00000000', max_length=8),
            preserve_default=False,
        ),
    ]
