# Generated by Django 6.0.5 on 2026-06-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_remove_rfidlog_uid_rfidlog_date_posted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
    ]
