# Generated by Django 6.0.5 on 2026-06-20 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_systemsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_scanned', models.CharField(max_length=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Present', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='RFIDLog',
        ),
        migrations.DeleteModel(
            name='SystemSetting',
        ),
        migrations.AddField(
            model_name='teammates',
            name='is_fully_registered',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teammates',
            name='rfid_number',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='teammate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.teammates'),
        ),
    ]
