# Generated by Django 6.0.5 on 2026-06-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_attendancelog_delete_rfidlog_delete_systemsetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='unregistered_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_number', models.CharField(max_length=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='attendancelog',
            old_name='rfid_scanned',
            new_name='rfid_number',
        ),
        migrations.AlterField(
            model_name='teammates',
            name='rfid_number',
            field=models.CharField(db_index=True, max_length=8, unique=True),
        ),
    ]
