# Generated by Django 6.0.6 on 2026-06-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_unregistered_log_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammates',
            name='rfid_number',
        ),
        migrations.AddField(
            model_name='teammates',
            name='domain',
            field=models.CharField(default='not_added', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='rfid_number',
            field=models.CharField(db_index=True, max_length=8, unique=True),
        ),
    ]
