# Generated by Django 6.0.6 on 2026-06-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_remove_teammates_rfid_number_teammates_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelog',
            name='rfid_number',
        ),
        migrations.AddField(
            model_name='teammates',
            name='rfid_number',
            field=models.CharField(db_index=True, default=0, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
